import type { FurnitureItem } from "@/types/furniture";

export const furnitureItems: FurnitureItem[] = [
  {
    id: "furn-sofa-01",
    title: "Диван Verona Compact",
    image: "/images/furniture/verona-compact.png",
    category: "sofa",
    room: "Кухня-гостиная",
    price: 84900,
    oldPrice: 103000,
    dimensions: "220 × 95 × 86 см",
    material: "велюр, массив березы, металл",
    color: "теплый бежевый",
    delivery: "7–12 дней",
    description: "Компактный диван для кухни-гостиной. Подходит для квартир евро-формата и сохраняет свободный проход.",
    tags: ["для приема гостей", "раскладной", "нейтральный цвет"]
  },
  {
    id: "furn-sofa-02",
    title: "Угловой диван Linea Family",
    image: "/images/furniture/linea-family.png",
    category: "sofa",
    room: "Гостиная",
    price: 126500,
    dimensions: "280 × 175 × 88 см",
    material: "рогожка, фанера, металл",
    color: "серо-песочный",
    delivery: "10–16 дней",
    description: "Угловой диван для просторной гостиной. Хорошо зонирует пространство и подходит для семейного отдыха.",
    tags: ["угловой", "семейный", "много посадочных мест"]
  },
  {
    id: "furn-bed-01",
    title: "Кровать Alba 160",
    image: "/images/furniture/alba-160.png",
    category: "bed",
    room: "Спальня",
    price: 58900,
    oldPrice: 69900,
    dimensions: "170 × 212 × 104 см",
    material: "МДФ, текстиль, ортопедическое основание",
    color: "светло-серый",
    delivery: "5–9 дней",
    description: "Кровать шириной 160 см для стандартной спальни. Оставляет место для тумб и шкафа.",
    tags: ["160 см", "мягкое изголовье", "для спальни"]
  },
  {
    id: "furn-bed-02",
    title: "Кровать Alba 180 Storage",
    image: "/images/furniture/alba-180-storage.png",
    category: "bed",
    room: "Мастер-спальня",
    price: 74900,
    dimensions: "190 × 215 × 108 см",
    material: "текстиль, подъемный механизм, ламели",
    color: "молочный",
    delivery: "8–14 дней",
    description: "Кровать 180 см с местом хранения. Подходит для мастер-спальни и помогает убрать сезонные вещи.",
    tags: ["180 см", "подъемный механизм", "хранение"]
  },
  {
    id: "furn-table-01",
    title: "Обеденный стол Nordic Round",
    image: "/images/furniture/nordic-round.png",
    category: "table",
    room: "Кухня-гостиная",
    price: 32900,
    dimensions: "Ø110 × 76 см",
    material: "шпон дуба, металл",
    color: "натуральный дуб",
    delivery: "4–8 дней",
    description: "Круглый стол на 4 человека. Удобен для небольших кухонь-гостиных и не перегружает проходы.",
    tags: ["на 4 персоны", "круглый", "дуб"]
  },
  {
    id: "furn-table-02",
    title: "Рабочий стол Slim Desk",
    image: "/images/furniture/slim-desk.png",
    category: "table",
    room: "Спальня / кабинет",
    price: 21900,
    dimensions: "120 × 55 × 75 см",
    material: "ЛДСП, металл",
    color: "белый матовый",
    delivery: "3–7 дней",
    description: "Узкий рабочий стол для спальни, детской или кабинета. Можно поставить у окна или в нише.",
    tags: ["рабочее место", "компактный", "для удаленной работы"]
  },
  {
    id: "furn-storage-01",
    title: "Шкаф Modul 240",
    image: "/images/furniture/modul-240.png",
    category: "storage",
    room: "Спальня / прихожая",
    price: 67500,
    dimensions: "240 × 62 × 235 см",
    material: "МДФ, зеркало, алюминиевый профиль",
    color: "кашемир + зеркало",
    delivery: "12–20 дней",
    description: "Высокий шкаф-купе с зеркальными фасадами. Подходит для спальни или просторной прихожей.",
    tags: ["шкаф-купе", "зеркало", "много хранения"]
  },
  {
    id: "furn-storage-02",
    title: "Гардеробная система Flexi 180",
    image: "/images/furniture/flexi-180.png",
    category: "storage",
    room: "Гардеробная",
    price: 45900,
    dimensions: "180 × 45 × 220 см",
    material: "металл, ЛДСП, сетчатые корзины",
    color: "графит",
    delivery: "6–10 дней",
    description: "Модульная система для гардеробной. Включает штанги, полки и выдвижные корзины.",
    tags: ["гардеробная", "модульная", "корзины"]
  },
  {
    id: "furn-kitchen-01",
    title: "Кухонный гарнитур Terra 3.2",
    image: "/images/furniture/terra-32.png",
    category: "kitchen",
    room: "Кухня",
    price: 158000,
    oldPrice: 189000,
    dimensions: "320 × 60 × 240 см",
    material: "МДФ эмаль, столешница HPL",
    color: "оливковый + дуб",
    delivery: "18–30 дней",
    description: "Линейная кухня 3,2 м с местом под встроенную технику. Хорошо подходит для кухни-гостиной.",
    tags: ["линейная кухня", "под встроенную технику", "HPL"]
  },
  {
    id: "furn-kitchen-02",
    title: "Кухонный остров Mini Island",
    image: "/images/furniture/mini-island.png",
    category: "kitchen",
    room: "Кухня-гостиная",
    price: 69900,
    dimensions: "140 × 80 × 92 см",
    material: "МДФ, кварцевый агломерат",
    color: "белый камень",
    delivery: "14–24 дня",
    description: "Компактный остров для просторной кухни-гостиной. Можно использовать как рабочую поверхность и барную зону.",
    tags: ["остров", "барная зона", "дополнительная поверхность"]
  },
  {
    id: "furn-bath-01",
    title: "Тумба под раковину Aqua 80",
    image: "/images/furniture/aqua-80.png",
    category: "bathroom",
    room: "Санузел",
    price: 28900,
    dimensions: "80 × 47 × 55 см",
    material: "влагостойкий МДФ, керамика",
    color: "белый глянец",
    delivery: "4–9 дней",
    description: "Подвесная тумба с двумя ящиками. Помогает организовать хранение в санузле без перегруза пространства.",
    tags: ["санузел", "подвесная", "2 ящика"]
  },
  {
    id: "furn-light-01",
    title: "Трековая система Light Line 4 м",
    image: "/images/furniture/light-line-4m.png",
    category: "lighting",
    room: "Кухня-гостиная / коридор",
    price: 34900,
    dimensions: "4 м, 8 светильников",
    material: "алюминий, LED-модули",
    color: "черный матовый",
    delivery: "3–6 дней",
    description: "Гибкая система освещения для зонирования кухни-гостиной, прихожей или коридора.",
    tags: ["трековый свет", "зонирование", "LED"]
  },
  {
    id: "furn-decor-01",
    title: "Комплект текстиля Soft Home",
    image: "/images/furniture/soft-home.png",
    category: "decor",
    room: "Спальня / гостиная",
    price: 15900,
    dimensions: "шторы, покрывало, 3 подушки",
    material: "лен, хлопок, велюр",
    color: "теплый песочный",
    delivery: "2–5 дней",
    description: "Готовый комплект текстиля для быстрого оформления спальни или гостиной в спокойной палитре.",
    tags: ["текстиль", "готовый комплект", "уют"]
  },
  {
    id: "furn-children-01",
    title: "Детская система Junior Set",
    image: "/images/furniture/junior-set.png",
    category: "storage",
    room: "Детская",
    price: 89900,
    dimensions: "кровать 90×200, шкаф, стол",
    material: "ЛДСП, МДФ, металл",
    color: "белый + светлое дерево",
    delivery: "10–18 дней",
    description: "Набор мебели для детской комнаты: кровать, шкаф и рабочий стол в едином стиле.",
    tags: ["детская", "комплект", "учебная зона"]
  }
];

export const furnitureCategoryLabels: Record<FurnitureItem["category"], string> = {
  sofa: "Диваны",
  bed: "Кровати",
  table: "Столы",
  storage: "Хранение",
  kitchen: "Кухни",
  bathroom: "Санузел",
  lighting: "Освещение",
  decor: "Декор"
};
