import type { FurnitureItem } from "@/types/furniture";

export const furnitureItems: FurnitureItem[] = [
  {
    id: "furn-sofa-01",
    title: "Диван Verona Compact",
    image: "/images/furniture/verona-compact.png",
    category: "sofa",
    room: "Кухня-гостиная",
    price: 84900,
    oldPrice: 103000,
    dimensions: "220 × 95 × 86 см",
    material: "велюр, массив березы, металл",
    color: "теплый бежевый",
    delivery: "7–12 дней",
    description: "Компактный диван для кухни-гостиной. Подходит для квартир евро-формата и сохраняет свободный проход.",
    tags: ["для приема гостей", "раскладной", "нейтральный цвет"]
  },
  {
    id: "furn-sofa-02",
    title: "Угловой диван Linea Family",
    image: "/images/furniture/linea-family.png",
    category: "sofa",
    room: "Гостиная",
    price: 126500,
    dimensions: "280 × 175 × 88 см",
    material: "рогожка, фанера, металл",
    color: "серо-песочный",
    delivery: "10–16 дней",
    description: "Угловой диван для просторной гостиной. Хорошо зонирует пространство и подходит для семейного отдыха.",
    tags: ["угловой", "семейный", "много посадочных мест"]
  },
  {
    id: "furn-bed-01",
    title: "Кровать Alba 160",
    image: "/images/furniture/alba-160.png",
    category: "bed",
    room: "Спальня",
    price: 58900,
    oldPrice: 69900,
    dimensions: "170 × 212 × 104 см",
    material: "МДФ, текстиль, ортопедическое основание",
    color: "светло-серый",
    delivery: "5–9 дней",
    description: "Кровать шириной 160 см для стандартной спальни. Оставляет место для тумб и шкафа.",
    tags: ["160 см", "мягкое изголовье", "для спальни"]
  },
  {
    id: "furn-bed-02",
    title: "Кровать Alba 180 Storage",
    image: "/images/furniture/alba-180-storage.png",
    category: "bed",
    room: "Мастер-спальня",
    price: 74900,
    dimensions: "190 × 215 × 108 см",
    material: "текстиль, подъемный механизм, ламели",
    color: "молочный",
    delivery: "8–14 дней",
    description: "Кровать 180 см с местом хранения. Подходит для мастер-спальни и помогает убрать сезонные вещи.",
    tags: ["180 см", "подъемный механизм", "хранение"]
  },
  {
    id: "furn-table-01",
    title: "Обеденный стол Nordic Round",
    image: "/images/furniture/nordic-round.png",
    category: "table",
    room: "Кухня-гостиная",
    price: 32900,
    dimensions: "Ø110 × 76 см",
    material: "шпон дуба, металл",
    color: "натуральный дуб",
    delivery: "4–8 дней",
    description: "Круглый стол на 4 человека. Удобен для небольших кухонь-гостиных и не перегружает проходы.",
    tags: ["на 4 персоны", "круглый", "дуб"]
  },
  {
    id: "furn-table-02",
    title: "Рабочий стол Slim Desk",
    image: "/images/furniture/slim-desk.png",
    category: "table",
    room: "Спальня / кабинет",
    price: 21900,
    dimensions: "120 × 55 × 75 см",
    material: "ЛДСП, металл",
    color: "белый матовый",
    delivery: "3–7 дней",
    description: "Узкий рабочий стол для спальни, детской или кабинета. Можно поставить у окна или в нише.",
    tags: ["рабочее место", "компактный", "для удаленной работы"]
  },
  {
    id: "furn-storage-01",
    title: "Шкаф Modul 240",
    image: "/images/furniture/modul-240.png",
    category: "storage",
    room: "Спальня / прихожая",
    price: 67500,
    dimensions: "240 × 62 × 235 см",
    material: "МДФ, зеркало, алюминиевый профиль",
    color: "кашемир + зеркало",
    delivery: "12–20 дней",
    description: "Высокий шкаф-купе с зеркальными фасадами. Подходит для спальни или просторной прихожей.",
    tags: ["шкаф-купе", "зеркало", "много хранения"]
  },
  {
    id: "furn-storage-02",
    title: "Гардеробная система Flexi 180",
    image: "/images/furniture/flexi-180.png",
    category: "storage",
    room: "Гардеробная",
    price: 45900,
    dimensions: "180 × 45 × 220 см",
    material: "металл, ЛДСП, сетчатые корзины",
    color: "графит",
    delivery: "6–10 дней",
    description: "Модульная система для гардеробной. Включает штанги, полки и выдвижные корзины.",
    tags: ["гардеробная", "модульная", "корзины"]
  },
  {
    id: "furn-kitchen-01",
    title: "Кухонный гарнитур Terra 3.2",
    image: "/images/furniture/terra-32.png",
    category: "kitchen",
    room: "Кухня",
    price: 158000,
    oldPrice: 189000,
    dimensions: "320 × 60 × 240 см",
    material: "МДФ эмаль, столешница HPL",
    color: "оливковый + дуб",
    delivery: "18–30 дней",
    description: "Линейная кухня 3,2 м с местом под встроенную технику. Хорошо подходит для кухни-гостиной.",
    tags: ["линейная кухня", "под встроенную технику", "HPL"]
  },
  {
    id: "furn-kitchen-02",
    title: "Кухонный остров Mini Island",
    image: "/images/furniture/mini-island.png",
    category: "kitchen",
    room: "Кухня-гостиная",
    price: 69900,
    dimensions: "140 × 80 × 92 см",
    material: "МДФ, кварцевый агломерат",
    color: "белый камень",
    delivery: "14–24 дня",
    description: "Компактный остров для просторной кухни-гостиной. Можно использовать как рабочую поверхность и барную зону.",
    tags: ["остров", "барная зона", "дополнительная поверхность"]
  },
  {
    id: "furn-bath-01",
    title: "Тумба под раковину Aqua 80",
    image: "/images/furniture/aqua-80.png",
    category: "bathroom",
    room: "Санузел",
    price: 28900,
    dimensions: "80 × 47 × 55 см",
    material: "влагостойкий МДФ, керамика",
    color: "белый глянец",
    delivery: "4–9 дней",
    description: "Подвесная тумба с двумя ящиками. Помогает организовать хранение в санузле без перегруза пространства.",
    tags: ["санузел", "подвесная", "2 ящика"]
  },
  {
    id: "furn-light-01",
    title: "Трековая система Light Line 4 м",
    image: "/images/furniture/light-line-4m.png",
    category: "lighting",
    room: "Кухня-гостиная / коридор",
    price: 34900,
    dimensions: "4 м, 8 светильников",
    material: "алюминий, LED-модули",
    color: "черный матовый",
    delivery: "3–6 дней",
    description: "Гибкая система освещения для зонирования кухни-гостиной, прихожей или коридора.",
    tags: ["трековый свет", "зонирование", "LED"]
  },
  {
    id: "furn-decor-01",
    title: "Комплект текстиля Soft Home",
    image: "/images/furniture/soft-home.png",
    category: "decor",
    room: "Спальня / гостиная",
    price: 15900,
    dimensions: "шторы, покрывало, 3 подушки",
    material: "лен, хлопок, велюр",
    color: "теплый песочный",
    delivery: "2–5 дней",
    description: "Готовый комплект текстиля для быстрого оформления спальни или гостиной в спокойной палитре.",
    tags: ["текстиль", "готовый комплект", "уют"]
  },
  {
    id: "furn-children-01",
    title: "Детская система Junior Set",
    image: "/images/furniture/junior-set.png",
    category: "storage",
    room: "Детская",
    price: 89900,
    dimensions: "кровать 90×200, шкаф, стол",
    material: "ЛДСП, МДФ, металл",
    color: "белый + светлое дерево",
    delivery: "10–18 дней",
    description: "Набор мебели для детской комнаты: кровать, шкаф и рабочий стол в едином стиле.",
    tags: ["детская", "комплект", "учебная зона"]
  },

  {
    id: "furn-sofa-03",
    title: "Кресло Lounge Solo",
    image: "/images/furniture/lounge-solo.png",
    category: "sofa",
    room: "Гостиная / лоджия",
    price: 38900,
    oldPrice: 45900,
    dimensions: "82 × 88 × 92 см",
    material: "букле, фанера, металл",
    color: "кремовый",
    delivery: "5–8 дней",
    description: "Мягкое кресло для зоны чтения, лоджии или дополнительного посадочного места в гостиной.",
    tags: ["кресло", "зона отдыха", "компактное"]
  },
  {
    id: "furn-sofa-04",
    title: "Пуф Storage Round",
    image: "/images/furniture/storage-round.png",
    category: "sofa",
    room: "Спальня / прихожая",
    price: 12900,
    dimensions: "Ø55 × 42 см",
    material: "велюр, фанера, съемная крышка",
    color: "терракотовый",
    delivery: "2–5 дней",
    description: "Пуф с внутренним хранением: удобен у кровати, в прихожей или рядом с диваном.",
    tags: ["пуф", "хранение", "маленькая площадь"]
  },
  {
    id: "furn-bed-03",
    title: "Кровать Simple 140",
    image: "/images/furniture/alba-160.png",
    category: "bed",
    room: "Спальня / студия",
    price: 42900,
    dimensions: "150 × 205 × 96 см",
    material: "ЛДСП, ткань, ортопедическое основание",
    color: "серо-бежевый",
    delivery: "4–8 дней",
    description: "Компактная кровать 140 см для небольшой спальни или студии, где важно сохранить проход.",
    tags: ["140 см", "компактная", "для студии"]
  },
  {
    id: "furn-bed-04",
    title: "Кровать Kids Cloud 90",
    image: "/images/furniture/junior-set.png",
    category: "bed",
    room: "Детская",
    price: 31900,
    dimensions: "98 × 205 × 84 см",
    material: "массив сосны, МДФ",
    color: "белый",
    delivery: "5–10 дней",
    description: "Детская кровать 90×200 см с бортиком и спокойным дизайном для учебной зоны рядом.",
    tags: ["детская", "90×200", "бортик"]
  },
  {
    id: "furn-table-03",
    title: "Журнальный стол Mono",
    image: "/images/furniture/nordic-round.png",
    category: "table",
    room: "Гостиная",
    price: 16900,
    dimensions: "90 × 55 × 38 см",
    material: "МДФ, шпон ясеня",
    color: "орех",
    delivery: "3–6 дней",
    description: "Невысокий столик для диванной зоны. Не перегружает комнату и подходит для малых гостиных.",
    tags: ["журнальный", "диванная зона", "компактный"]
  },
  {
    id: "furn-table-04",
    title: "Консоль Entry 100",
    image: "/images/furniture/slim-desk.png",
    category: "table",
    room: "Прихожая / коридор",
    price: 18900,
    dimensions: "100 × 35 × 82 см",
    material: "металл, МДФ",
    color: "черный + дуб",
    delivery: "3–7 дней",
    description: "Узкая консоль для ключей, декора и мелочей в прихожей без перекрытия прохода.",
    tags: ["консоль", "прихожая", "узкая"]
  },
  {
    id: "furn-table-05",
    title: "Стол Transform 6",
    image: "/images/furniture/nordic-round.png",
    category: "table",
    room: "Кухня-гостиная",
    price: 47900,
    oldPrice: 54900,
    dimensions: "120/170 × 80 × 76 см",
    material: "керамогранит, металл",
    color: "светлый камень",
    delivery: "7–12 дней",
    description: "Раздвижной обеденный стол: в обычный день компактный, а для гостей увеличивается до 170 см.",
    tags: ["раздвижной", "на 4–6 персон", "для гостей"]
  },
  {
    id: "furn-storage-03",
    title: "Комод Line 160",
    image: "/images/furniture/line-160.png",
    category: "storage",
    room: "Спальня / гостиная",
    price: 38900,
    dimensions: "160 × 45 × 82 см",
    material: "МДФ, направляющие soft-close",
    color: "теплый графит",
    delivery: "7–12 дней",
    description: "Низкий комод для белья, документов и бытовых вещей. Может заменить часть шкафа в небольшой спальне.",
    tags: ["комод", "soft-close", "хранение"]
  },
  {
    id: "furn-storage-04",
    title: "Стеллаж Open Rack 90",
    image: "/images/furniture/open-rack-90.png",
    category: "storage",
    room: "Кабинет / детская",
    price: 24900,
    dimensions: "90 × 35 × 190 см",
    material: "ЛДСП, металл",
    color: "белый + графит",
    delivery: "3–7 дней",
    description: "Открытый стеллаж для книг, декора и рабочих материалов. Подходит для кабинета или детской.",
    tags: ["стеллаж", "книги", "кабинет"]
  },
  {
    id: "furn-storage-05",
    title: "Обувница Hall Slim",
    image: "/images/furniture/hall-slim.png",
    category: "storage",
    room: "Прихожая",
    price: 22900,
    dimensions: "110 × 28 × 105 см",
    material: "МДФ, металлические корзины",
    color: "кашемир",
    delivery: "4–8 дней",
    description: "Узкая обувница для прихожей: хранит обувь и не мешает открыванию входной двери.",
    tags: ["обувница", "прихожая", "узкая"]
  },
  {
    id: "furn-storage-06",
    title: "Шкаф Corner Max",
    image: "/images/furniture/modul-240.png",
    category: "storage",
    room: "Спальня / детская",
    price: 79900,
    dimensions: "160 × 160 × 235 см",
    material: "ЛДСП, МДФ, зеркало",
    color: "белый + зеркало",
    delivery: "14–22 дня",
    description: "Угловой шкаф для комнат, где нужно много хранения и нельзя занимать длинную стену.",
    tags: ["угловой шкаф", "много хранения", "зеркало"]
  },
  {
    id: "furn-kitchen-03",
    title: "Кухня Compact 2.4",
    image: "/images/furniture/terra-32.png",
    category: "kitchen",
    room: "Кухня / студия",
    price: 119000,
    dimensions: "240 × 60 × 240 см",
    material: "ЛДСП, HPL-столешница",
    color: "белый + светлый дуб",
    delivery: "14–25 дней",
    description: "Компактный кухонный гарнитур для студии или небольшой кухни-гостиной с местом под встроенную технику.",
    tags: ["компактная кухня", "для студии", "HPL"]
  },
  {
    id: "furn-kitchen-04",
    title: "Барная стойка Loft 120",
    image: "/images/furniture/loft-120.png",
    category: "kitchen",
    room: "Кухня-гостиная",
    price: 41900,
    dimensions: "120 × 55 × 92 см",
    material: "металл, шпон дуба",
    color: "черный + дуб",
    delivery: "5–9 дней",
    description: "Барная стойка для зонирования кухни-гостиной и быстрых завтраков без большого стола.",
    tags: ["барная зона", "зонирование", "компактная"]
  },
  {
    id: "furn-bath-02",
    title: "Пенал Aqua Tall",
    image: "/images/furniture/aqua-modern.png",
    category: "bathroom",
    room: "Санузел",
    price: 31900,
    dimensions: "40 × 35 × 180 см",
    material: "влагостойкий МДФ",
    color: "серый шелк",
    delivery: "5–10 дней",
    description: "Узкий пенал для полотенец, бытовой химии и средств ухода в санузле.",
    tags: ["пенал", "санузел", "узкое хранение"]
  },
  {
    id: "furn-bath-03",
    title: "Зеркальный шкаф Mirror 70",
    image: "/images/furniture/aqua-80.png",
    category: "bathroom",
    room: "Санузел",
    price: 19900,
    dimensions: "70 × 16 × 75 см",
    material: "зеркало, влагостойкий корпус, LED",
    color: "белый",
    delivery: "3–7 дней",
    description: "Зеркальный шкаф с подсветкой и полками для хранения ежедневных средств.",
    tags: ["зеркало", "LED", "санузел"]
  },
  {
    id: "furn-light-02",
    title: "Люстра Soft Ring",
    image: "/images/furniture/soft-ring.png",
    category: "lighting",
    room: "Спальня / гостиная",
    price: 26900,
    dimensions: "Ø65 см, LED",
    material: "металл, акрил",
    color: "латунь + белый",
    delivery: "3–6 дней",
    description: "Мягкий потолочный свет для спальни или гостиной, подходит к спокойным современным интерьерам.",
    tags: ["люстра", "мягкий свет", "LED"]
  },
  {
    id: "furn-light-03",
    title: "Бра Bedside Pair",
    image: "/images/furniture/light-line-4m.png",
    category: "lighting",
    room: "Спальня",
    price: 14900,
    dimensions: "2 светильника, 18 × 12 × 28 см",
    material: "металл, тканевый абажур",
    color: "черный + лен",
    delivery: "2–5 дней",
    description: "Пара настенных бра для чтения у кровати без лишних проводов на тумбах.",
    tags: ["бра", "у кровати", "пара"]
  },
  {
    id: "furn-decor-02",
    title: "Ковер Calm 200",
    image: "/images/furniture/calm-textile.png",
    category: "decor",
    room: "Гостиная / спальня",
    price: 23900,
    dimensions: "200 × 300 см",
    material: "шерсть, хлопок",
    color: "светлый беж",
    delivery: "4–9 дней",
    description: "Ковер для мягкого зонирования диванной зоны или спальни и повышения акустического комфорта.",
    tags: ["ковер", "зонирование", "уют"]
  },
  {
    id: "furn-decor-03",
    title: "Шторы Blackout Set",
    image: "/images/furniture/calm-textile.png",
    category: "decor",
    room: "Спальня / детская",
    price: 18900,
    dimensions: "2 полотна 150 × 270 см",
    material: "blackout-ткань, лен",
    color: "пыльно-синий",
    delivery: "3–6 дней",
    description: "Комплект плотных штор для спальни или детской: помогает затемнить комнату и добавить приватность.",
    tags: ["шторы", "blackout", "приватность"]
  },
  {
    id: "furn-decor-04",
    title: "Балконный набор Loggia Relax",
    image: "/images/furniture/loggia-relax.png",
    category: "decor",
    room: "Лоджия",
    price: 27900,
    dimensions: "кресло, столик, 2 подушки",
    material: "ротанг, металл, уличная ткань",
    color: "натуральный ротанг",
    delivery: "4–8 дней",
    description: "Комплект для лоджии: компактное кресло, столик и подушки для зоны кофе или чтения.",
    tags: ["лоджия", "зона отдыха", "комплект"]
  },
];

export const furnitureCategoryLabels: Record<FurnitureItem["category"], string> = {
  sofa: "Диваны",
  bed: "Кровати",
  table: "Столы",
  storage: "Хранение",
  kitchen: "Кухни",
  bathroom: "Санузел",
  lighting: "Освещение",
  decor: "Декор"
};
